name: "Compose DevOps Healthcheck"
description: "Runs docker compose and validates container health"
author: "Yaraslau Lazakovich"

branding:
  icon: "check-circle"
  color: "blue"

inputs:
  compose-files:
    description: "List of docker-compose files (one per line)"
    required: true
    default: |
      docker-compose.yml
  compose-services:
    description: "List of services to check (space-separated). Defaults to all services when omitted; ignored when docker-command is set."
    required: false
    default: ""
  services:
    description: "DEPRECATED: use compose-services."
    required: false
    default: ""
  timeout:
    description: "Healthcheck timeout per service in seconds"
    required: false
    default: "120"
  log-lines:
    description: "Number of healthcheck/container log lines to show on failure"
    required: false
    default: "25"
  additional-compose-args:
    description: "Additional args for docker compose (e.g. --quiet-pull or --build)"
    required: false
    default: ""
  compose-profiles:
    description: "One or more compose profiles (space or newline separated). Ignored when docker-command is set."
    required: false
    default: ""
  docker-command:
    description: "Full docker compose command to execute instead of compose-files/services (e.g. docker compose -f docker-compose.yml up -d web)"
    required: false
    default: ""
  report-format:
    description: "Healthcheck report format: text | json | both"
    required: false
    default: "text"

outputs:
  summary_b64:
    description: "Base64-encoded human-readable output of healthcheck"
    value: ${{ steps.run_healthcheck.outputs.summary_b64 }}
  report_json_b64:
    description: "Base64-encoded machine-readable JSON healthcheck report (when enabled)"
    value: ${{ steps.run_healthcheck.outputs.report_json_b64 }}

runs:
  using: "composite"
  steps:
    - id: run_healthcheck
      name: Run docker compose with health check
      shell: bash
      env:
        DOCKER_HEALTH_TIMEOUT: ${{ inputs.timeout }}
        DOCKER_HEALTH_LOG_LINES: ${{ inputs.log-lines }}
        DOCKER_SERVICES_LIST: ${{ inputs.compose-services }}
        DOCKER_HEALTH_REPORT_FORMAT: ${{ inputs.report-format }}
      run: |
        set -euo pipefail

        SCRIPT_DIR="${GITHUB_ACTION_PATH}"

        compose_files_input="${{ inputs.compose-files }}"
        additional_args_input="${{ inputs.additional-compose-args }}"
        compose_services_input="${{ inputs.compose-services }}"
        services_input="${{ inputs.services }}"
        report_format_input="${{ inputs.report-format }}"
        docker_command_input="${{ inputs.docker-command }}"
        compose_profiles_input="${{ inputs.compose-profiles }}"

        if [[ -n "$compose_services_input" ]]; then
          services_input="$compose_services_input"
        fi

        if [[ -n "$services_input" ]]; then
          export DOCKER_SERVICES_LIST="$services_input"
        fi

        if [[ -n "$docker_command_input" ]]; then
          unset DOCKER_SERVICES_LIST
        fi

        mapfile -d '' -t CMD < <(
          COMPOSE_FILES_INPUT="$compose_files_input" \
          ADDITIONAL_COMPOSE_ARGS_INPUT="$additional_args_input" \
          COMPOSE_SERVICES_INPUT="$compose_services_input" \
          SERVICES_INPUT="$services_input" \
          COMPOSE_PROFILES_INPUT="$compose_profiles_input" \
          DOCKER_COMMAND_INPUT="$docker_command_input" \
          bash "${SCRIPT_DIR}/lib/build-compose-command.sh"
        )

        TMP_OUT="$(mktemp)"
        JSON_TMP="$(mktemp)"

        # Tell the healthcheck script where to write JSON (if report-format is json/both).
        export DOCKER_HEALTH_REPORT_JSON_FILE="$JSON_TMP"
        export DOCKER_HEALTH_REPORT_FORMAT="$report_format_input"

        set +e
        bash "${SCRIPT_DIR}/entrypoint.sh" "${CMD[@]}" 2>&1 | tee "$TMP_OUT"
        rc=${PIPESTATUS[0]}
        set -e

        OUTPUT_B64="$(base64 <"$TMP_OUT" | tr -d '\n')"
        echo "summary_b64=$OUTPUT_B64" >>"$GITHUB_OUTPUT"

        # JSON output is optional; only publish if present and non-empty
        if [[ -s "$JSON_TMP" ]]; then
          JSON_B64="$(base64 <"$JSON_TMP" | tr -d '\n')"
          echo "report_json_b64=$JSON_B64" >>"$GITHUB_OUTPUT"
        else
          echo "report_json_b64=" >>"$GITHUB_OUTPUT"
        fi

        rm -f "$TMP_OUT" "$JSON_TMP"
        exit "$rc"
