name: "Compose DevOps Healthcheck"
description: "Runs docker compose and validates container health"
author: "Yaraslau Lazakovich"

branding:
  icon: "check-circle"
  color: "blue"

inputs:
  compose-files:
    description: "List of docker-compose files (one per line)"
    required: true
    default: |
      docker-compose.yml
  services:
    description: "List of services to start (space-separated)."
    required: true
    default: ""
  timeout:
    description: "Healthcheck timeout per service in seconds"
    required: false
    default: "120"
  additional-compose-args:
    description: "Additional args for docker compose (e.g. --quiet-pull or --build)"
    required: false
    default: ""
  report-format:
    description: "Healthcheck report format: text | json | both"
    required: false
    default: "text"

outputs:
  summary_b64:
    description: "Base64-encoded human-readable output of healthcheck"
    value: ${{ steps.run_healthcheck.outputs.summary_b64 }}
  report_json_b64:
    description: "Base64-encoded machine-readable JSON healthcheck report (when enabled)"
    value: ${{ steps.run_healthcheck.outputs.report_json_b64 }}

runs:
  using: "composite"
  steps:
    - id: run_healthcheck
      name: Run docker compose with health check
      shell: bash
      env:
        DOCKER_HEALTH_TIMEOUT: ${{ inputs.timeout }}
        DOCKER_SERVICES_LIST: ${{ inputs.services }}
        DOCKER_HEALTH_REPORT_FORMAT: ${{ inputs.report-format }}
      run: |
        set -euo pipefail

        SCRIPT_DIR="${GITHUB_ACTION_PATH}"

        compose_files_input="${{ inputs.compose-files }}"
        additional_args_input="${{ inputs.additional-compose-args }}"
        services_input="${{ inputs.services }}"
        report_format_input="${{ inputs.report-format }}"

        CMD=(docker compose)

        while IFS= read -r file; do
          if [[ -n "$file" ]]; then
            CMD+=(-f "$file")
          fi
        done <<<"$compose_files_input"

        CMD+=(up -d)

        if [[ -n "$additional_args_input" ]]; then
          extra_args=( $additional_args_input )
          CMD+=("${extra_args[@]}")
        fi

        if [[ -n "$services_input" ]]; then
          svc_arr=( $services_input )
          CMD+=("${svc_arr[@]}")
        fi

        TMP_OUT="$(mktemp)"
        JSON_TMP="$(mktemp)"

        # Tell the healthcheck script where to write JSON (if report-format is json/both).
        export DOCKER_HEALTH_REPORT_JSON_FILE="$JSON_TMP"
        export DOCKER_HEALTH_REPORT_FORMAT="$report_format_input"

        set +e
        bash "${SCRIPT_DIR}/entrypoint.sh" "${CMD[@]}" 2>&1 | tee "$TMP_OUT"
        rc=${PIPESTATUS[0]}
        set -e

        OUTPUT_B64="$(base64 <"$TMP_OUT" | tr -d '\n')"
        echo "summary_b64=$OUTPUT_B64" >>"$GITHUB_OUTPUT"

        # JSON output is optional; only publish if present and non-empty
        if [[ -s "$JSON_TMP" ]]; then
          JSON_B64="$(base64 <"$JSON_TMP" | tr -d '\n')"
          echo "report_json_b64=$JSON_B64" >>"$GITHUB_OUTPUT"
        else
          echo "report_json_b64=" >>"$GITHUB_OUTPUT"
        fi

        rm -f "$TMP_OUT" "$JSON_TMP"
        exit "$rc"
