runs:
  using: "composite"
  steps:
    - id: run_healthcheck
      name: Run docker compose with health check
      shell: bash
      env:
        DOCKER_HEALTH_TIMEOUT: ${{ inputs.timeout }}
        DOCKER_SERVICES_LIST: ${{ inputs.services }}
      run: |
        set -euo pipefail

        SCRIPT_DIR="${GITHUB_ACTION_PATH}"

        project_dir="${{ inputs.compose-project-directory }}"
        if [[ -z "$project_dir" || "$project_dir" == "." ]]; then
          project_dir="${GITHUB_WORKSPACE}"
        fi

        compose_files_input="${{ inputs.compose-files }}"
        additional_args_input="${{ inputs.additional-compose-args }}"
        services_input="${{ inputs.services }}"

        CMD=(docker compose)

        while IFS= read -r file; do
          if [[ -n "$file" ]]; then
            CMD+=(-f "$file")
          fi
        done <<<"$compose_files_input"

        if [[ -n "$additional_args_input" ]]; then
          extra_args=( $additional_args_input )
          CMD+=("${extra_args[@]}")
        fi

        CMD+=(up -d)

        if [[ -n "$services_input" ]]; then
          svc_arr=( $services_input )
          CMD+=("${svc_arr[@]}")
        fi

        echo "Running docker compose via docker_health_check.sh with command:"
        printf '  %q' "${CMD[@]}"
        echo

        TMP_OUT="$(mktemp)"

        set +e
        bash "${SCRIPT_DIR}/docker_health_check.sh" "${CMD[@]}" 2>&1 | tee "$TMP_OUT"
        rc=${PIPESTATUS[0]}
        set -e

        OUTPUT_B64="$(base64 <"$TMP_OUT" | tr -d '\n')"
        echo "summary_b64=$OUTPUT_B64" >>"$GITHUB_OUTPUT"

        rm -f "$TMP_OUT"

        exit "$rc"
