name: "Docker Compose Health Check"
description: "Runs docker compose and validates container health"
author: "Yaraslau Lazakovich"

inputs:
  compose-files:
    description: "List of docker-compose files (one per line)"
    required: false
    default: |
      docker-compose.yml
  services:
    description: "List of services to start (space-separated)."
    required: false
    default: ""
  timeout:
    description: "Healthcheck timeout per service in seconds"
    required: false
    default: "120"
  additional-compose-args:
    description: "Additional args for docker compose (e.g. --quiet-pull or --build)"
    required: false
    default: ""

outputs:
  summary_b64:
    description: "Base64-encoded output of healthcheck"
    value: ${{ steps.run_healthcheck.outputs.summary_b64 }}

runs:
  using: "composite"
  steps:
    - id: run_healthcheck
      name: Run docker compose with health check
      shell: bash
      env:
        DOCKER_HEALTH_TIMEOUT: ${{ inputs.timeout }}
        DOCKER_SERVICES_LIST: ${{ inputs.services }}
      run: |
        set -euo pipefail

        SCRIPT_DIR="${GITHUB_ACTION_PATH}"

        compose_files_input="${{ inputs.compose-files }}"
        additional_args_input="${{ inputs.additional-compose-args }}"
        services_input="${{ inputs.services }}"

        CMD=(docker compose)

        while IFS= read -r file; do
          if [[ -n "$file" ]]; then
            CMD+=(-f "$file")
          fi
        done <<<"$compose_files_input"

        if [[ -n "$additional_args_input" ]]; then
          extra_args=( $additional_args_input )
          CMD+=("${extra_args[@]}")
        fi

        CMD+=(up -d)

        if [[ -n "$services_input" ]]; then
          svc_arr=( $services_input )
          CMD+=("${svc_arr[@]}")
        fi

        TMP_OUT="$(mktemp)"

        set +e
        bash "${SCRIPT_DIR}/docker_health_check.sh" "${CMD[@]}" 2>&1 | tee "$TMP_OUT"
        rc=${PIPESTATUS[0]}
        set -e

        OUTPUT_B64="$(base64 <"$TMP_OUT" | tr -d '\n')"
        echo "summary_b64=$OUTPUT_B64" >>"$GITHUB_OUTPUT"

        rm -f "$TMP_OUT"

        exit "$rc"
